# Generated by Django 5.2.5 on 2025-08-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_page_app', '0002_remove_categoria_descricao_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
