# Generated by Django 5.2.5 on 2025-08-27 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_page_app', '0004_anoletivo_disciplina_semana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nome_abreviado', models.CharField(max_length=50, verbose_name='NomeAbreviado')),
                ('duracao', models.PositiveIntegerField(verbose_name='Duracao')),
                ('descricao', models.TextField(verbose_name='Descricao')),
            ],
        ),
        migrations.AlterModelOptions(
            name='anoletivo',
            options={'verbose_name_plural': 'Ano Letivo'},
        ),
        migrations.RemoveField(
            model_name='anoletivo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='id',
        ),
        migrations.RemoveField(
            model_name='semana',
            name='id',
        ),
        migrations.AlterField(
            model_name='anoletivo',
            name='ano',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.PositiveIntegerField(verbose_name='Carga Horaria'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='descricao',
            field=models.TextField(verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='semana',
            name='semana',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('registro_academico', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('senha', models.CharField(max_length=30)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_page_app.curso')),
            ],
        ),
    ]
