# Generated by Django 5.2.5 on 2025-08-27 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_page_app', '0005_curso_alter_anoletivo_options_remove_anoletivo_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Consumidor',
        ),
    ]
