# Generated by Django 5.2.5 on 2025-08-27 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_page_app', '0006_rename_usuario_consumidor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumidor',
            options={'verbose_name_plural': 'Consumidores'},
        ),
        migrations.AddField(
            model_name='consumidor',
            name='dt_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='consumidor',
            name='dt_insercao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
