# Generated by Django 5.2.5 on 2025-08-27 20:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_page_app', '0007_alter_consumidor_options_consumidor_dt_atualizacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumidor',
            name='dt_atualizacao',
        ),
        migrations.RemoveField(
            model_name='consumidor',
            name='dt_insercao',
        ),
        migrations.AddField(
            model_name='consumidor',
            name='data_atualizacao',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='consumidor',
            name='data_insercao',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
