# Generated by Django 5.2.5 on 2025-09-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_page_app', '0008_remove_consumidor_dt_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumidor',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='data_insercao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
