# Generated by Django 5.2.6 on 2025-09-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_page_app', '0009_alter_consumidor_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='quantidade_aulas_semanais',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade Aulas Semanais'),
        ),
    ]
